inc:
  # Blog Information
  title:        "Creative Nightly"
  subtitle:     "Random musings, and experimental blog of Scotty Vernon" #"Creative coding and inspiration"
  colophon:     false  #"Setup as a digital scrapbook of notes by Scotty Vernon @KingScooty"
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Creative Nightly
  url:          http://creativenightly.com/
  facebook:     null
  twitter:      kingscooty
  gplus:        '101183822199340201470'
  about_link:   false

  # Product Information
  product_link: false
  tagline:      false

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  scottyvernon

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         false


 # Analytics     
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: false

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://creativenightly.com
source:      .
destination: ./_site
plugins:     null
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['node_modules', 'bower.json', 'package.json', 'Rakefile', 'gulpfile.js', 'README.md']
timezone:    null

# Show future posts
future:      false
show_drafts: false
limit_posts: 0
highlighter: pygments

relative_permalinks: true

permalink: /:year/:month/:title
paginate_path: 'page:num'
paginate: 10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
#baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#

#sass:
#    sass_dir: assets/_sass
#    style: :compressed

# assets:

#   dirname: assets
#   baseurl: /assets/
#   sources:
#     - _assets/javascripts
#     - _assets/stylesheets
#     - _assets/images
#   js_compressor: uglifier
#   css_compressor: sass
#   cachebust: none
#   cache: false
#   gzip: [ text/css, application/javascript ]
#   debug: false