environment: production
production: true

inc:
  # Blog Information
  title:        "Creative Nightly"
  subtitle:     "@KingScooty's crusade to stay on top of the ever expanding/advancing web tech industry"
  #"A developer's account on the world of digital."
  #"Creative coding and inspiration" #A blog for creative, digital and technical explorers.
  colophon:     false
  cover_image:  blog-cover.jpg
  logo:         logo.png

  # Company information
  company:      Creative Nightly
  url:          http://www.creativenightly.com/
  facebook:     null
  twitter:      kingscooty
  gplus:        '101183822199340201470'
  about_link:   false

  # Product Information
  product_link: false
  tagline:      false

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  scottyvernon

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         false

 # Analytics
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: false

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

include: ['_pages']
# collections:
#   pages:
#     output: true

gems:
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-paginate

url:         http://www.creativenightly.com
source:      .
# destination: ./_site
# plugins:     null
layouts_dir:     ./_layouts
# include:     ['.htaccess']
exclude:     ['node_modules', 'bower.json', 'package.json', 'Rakefile', 'gulpfile.js', 'README.md']
timezone:    Europe/London

# Show future posts
future:      false
show_drafts: false
limit_posts: 0
highlighter: pygments

# relative_permalinks: true
relative_permalinks: false

permalink: /:year/:month/:title/
paginate_path: 'page:num'
paginate: 10

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
#baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: ["strikethrough"]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true




author:
  name: Scotty Vernon
  twitter: KingScooty
  gplus: +ScottyVernon
  bio: Founder, Software Engineer @ Wildflame Studios
  image: ks.png
